name: CI

on: [push, pull_request, repository_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Run a one-line script
      run: |
        echo ${{ secrets.A_SECRET }}
        echo ${{ secrets.A_SECRET }} | rev

# some change
