# Hey!
name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Run a one-line script
      run: |
        echo ${{ secrets.A_SECRET }}
        echo ${{ secrets.A_SECRET }} | rev
